# Generated by Django 3.0.6 on 2020-05-25 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=20)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('market_capital', models.FloatField(blank=True, null=True)),
                ('no_of_stocks', models.IntegerField()),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=20)),
                ('Lname', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('acc_balance', models.FloatField(default=500000.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockQuotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('Open', models.FloatField()),
                ('dayHigh', models.FloatField()),
                ('dayLow', models.FloatField()),
                ('lastPrice', models.FloatField()),
                ('previousClose', models.FloatField()),
                ('change', models.FloatField()),
                ('pChange', models.FloatField()),
                ('yearHigh', models.FloatField()),
                ('yearLow', models.FloatField()),
                ('chartTodayPath', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stock_quotes',
            },
        ),
        migrations.CreateModel(
            name='TradeShares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=5, null=True)),
                ('bid', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aa.Profile')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aa.StockQuotes')),
            ],
            options={
                'db_table': 'trade_shares',
            },
        ),
    ]
