# Generated by Django 3.0.6 on 2020-05-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeshares',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
