# Generated by Django 3.0.6 on 2020-05-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0002_tradeshares_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockquotes',
            old_name='change',
            new_name='Change',
        ),
    ]
