# Generated by Django 3.0.6 on 2020-06-01 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0004_auto_20200601_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aa.Profile')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aa.StockQuotes')),
            ],
        ),
    ]
