# Generated by Django 3.0.6 on 2020-06-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0005_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockquotes',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
