# Generated by Django 3.0.6 on 2020-06-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0006_auto_20200601_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockquotes',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
